### ISSUE TITLE
Consider pulling some of the data in `data-raw` in real time

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#12]
It would slow code down a little bit, but if there's a chance that some of the data that's in `data-raw` will be updated over time, we may want to consider writing a function to pull that data from online when a user needs it rather than having a static version saved within the package.

**Comment by rodlammers** [comment]
I agree but unfortunately the data isn't (currently) available in an easy to access format. The flood stage values are stored in a GIS shapefile which I had to download and open in ArcMap to extract the data. I then had to write an R script to pull stage-discharge relationships for all the gages to convert these stages to discharges. This code took a long time to run since there are so many gages. Honestly, the flood stage values shouldn't get updated by the NWS that often but it might just be part of the package maintenance to redo this analysis every year or two.

**Comment by geanders** [comment]
Nope, that sounds like a pain to do in real time. Sounds like a good strategy for us to keep a fairly recent version locally, rather than pull in real time. 

Also, do we need all of the columns in that data? It would save us a little space if we only kept columns we use later.

**Comment by rodlammers** [comment]
I think I can reduce the number of columns in the "NWS Flood Discharge Data.txt" file. This is the one used by the package. The other text files and R code show how I did the analysis to get the flood discharge data. This will be useful for updating the dataset in the future.

**Comment by geanders** [comment]
Yes, let's definitely keep the code for cleaning. I agree that will be useful.
