### ISSUE TITLE
How does a function recognize inputs that aren't explicitly labeled?

### ISSUE THREAD

**Issue by rodlammers** [rodlammers/countyfloods#14]
This is mostly an issue for the `run_flood` function. If I don't explicitly identify the inputs (e.g. `run_flood(county_cd = county_cd, start_date = start_date, ...)`) and instead just provide the variable names, the function can't figure out which input is which. It seems like a pretty standard R practice that functions can figure out the right inputs but does that require some special code within the function itself?

**Comment by geanders** [comment]
R will do them by the order they were defined in the function if you don't explicitly identify each input. Usually the safest, especially when you're using your own functions within other functions, is to explicitly id each argument, rather than relying on position. So, if a function is defined so that the order of parameters is `county_cd`, `start_date`, ..., then R will get it right if you run either of these three:

```
run_flood(county_cd, start_date, ...)
run_flood(county_cd = county_cd, start_date = start_date, ...)
run_flood(start_date = start_date, county_cd = county_cd, ...)
```

but not if you put in: 

```
run_flood(start_date, county_cd, ...)
```

Does that answer what you were asking about, or did I misunderstand your questions?

**Comment by rodlammers** [comment]
That is exactly what I was asking. I thought it was just by order but I guess the issue is that the `run_flood` function has inputs that might not be used (e.g. `county_cd`, `state`, and `flood_type`), they really have to be explicitly labeled. Since this will be the function most applied by the user, is it a problem to require explicit naming of the inputs?

**Comment by geanders** [comment]
I don't think so. We'll just want to make that very clear in the documentation.

**Comment by rodlammers** [comment]
Sounds good.

**Comment by geanders** [comment]
Also, between `state` and `county_cd`, let's put `county_cd` first in the function definition, since that might be the one people are more likely to want to use since this package is geared for county exposure classification.

**Comment by rodlammers** [comment]
I believe `county_cd` is currently first.

**Comment by geanders** [comment]
Sounds great-- I think we're all set with that, then.
