### ISSUE TITLE
Pull longer time periods of flow data

### ISSUE THREAD

**Issue by rodlammers** [rodlammers/countyfloods#20]
If I understood you correctly, you want to initially pull longer time series of data (e.g. 20 years) and then do the flood analysis on date range subsets that the user specifies. This would eliminate the need to make multiple calls to the USGS database to get the flow data. However, this is only useful if you are going to be analyzing multiple distinct date ranges for an individual gage. Is this the type of analysis you were envisioning? The simplest way would be to add date ranges to the `flood_analysis` function and the user would essentially go through all the steps in the `run_flood` function by hand. Otherwise, we could write a new function to get and store the long range flow data and then maybe iteratively run the `flood_analysis` function based on a dataframe of date ranges.

**Comment by geanders** [comment]
Yes. So, for example, I would want to pull data for all monitors in Miami-Dade county for 1988-2012, then I would use something else to get every date that a hurricane came within 200 km of the county, and I would want to be able to get those aggregated summaries of any flooding in the county's stream gages for some time period (a week or month, for example) around each hurricane. By pulling the data from USGS just once for the whole 1988-2012 period, and then running the aggregation for smaller time windows, it would save time since accessing the data seems to be the slowest part of the process.

**Comment by rodlammers** [comment]
OK, I'm imagining the user providing a dataframe as input with a column of county codes and a column of data ranges (with the option of multiple date ranges per county). Then, the code can find the oldest and most recent dates, pull all that data, and do the analysis individually on each data range. How does that sound?

**Comment by geanders** [comment]
That's exactly the kind of thing I was thinking. That would be awesome.

**Comment by rodlammers** [comment]
I've finished the `long_term_flood` function which accepts a data frame of county codes, start dates, and end dates and returns output of flooding during each date range by gage and by county. It currently doesn't handle state names as a column in the `input_df` but I think I could add that functionality.

As a general note, if you feel any of these functions/inputs should be renamed feel free to change them. I'm definitely not attached to any of them and you could probably come up with something more applicable.
