### ISSUE TITLE
Add reference in help documentation for the Weibull plotting method

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#9]
Specifically, I think we want to add a note in the documentation and a reference to explain this part of the method of our code: 

```
# use values to construct probability plot using the Weibull plotting method
```

(in `find_Q2`)

**Comment by geanders** [comment]
Also, we may want to nose around and see if R already has a function for doing this. If so, we could replace the `construct_prob_plot` I added with that. Given that this is a statistical procedure, I'd be a little surprised if there's not a function for this yet.

**Comment by rodlammers** [comment]
Just from a quick search, it seems that most of the existing R functions out there fit a theoretical Weibull distribution to the data. What our function does is create an empirical distribution using only the rank order of the data (i.e. it doesn't compute a shape and scale parameter based on the data). Since this approach is standard in hydrology, I think leaving the function as is is preferred. I can add documentation explaining the procedure.
